// Static fallback packages for auto-seeding when database is empty
// Used in: billing.service.ts, register page, and seed API

export const STATIC_PACKAGES = [
  {
    id: 'pkg_trial',
    name: '1-Month Free Trial',
    description: 'Trial TradeCandle Gold Scalper v12 Free 30 days — 1 MT5 Accounts + Dashboard + 3-Wave Cashout',
    priceCents: 0,
    currency: 'USD',
    billingCycle: 'MONTHLY',
    maxAccounts: 1,
    features: '{"strategyIds":["strat_v12"],"priority":1,"emailSupport":true,"dashboard":true}',
    isActive: true,
    isTrial: true,
    trialDays: 30,
    sortOrder: 0,
  },
  {
    id: 'pkg_starter',
    name: 'Starter',
    description: 'For Beginner Traders 1 MT5 Accounts — 3-Wave Cashout + Dashboard',
    priceCents: 999,
    currency: 'USD',
    billingCycle: 'MONTHLY',
    maxAccounts: 1,
    features: '{"strategyIds":["strat_v12"],"priority":1,"emailSupport":true,"dashboard":true}',
    isActive: true,
    isTrial: false,
    trialDays: 0,
    sortOrder: 1,
  },
  {
    id: 'pkg_pro',
    name: 'Pro',
    description: 'For Serious Traders 3 Accounts — Kill Switch + Risk Management + Line Support',
    priceCents: 2499,
    currency: 'USD',
    billingCycle: 'MONTHLY',
    maxAccounts: 3,
    features: '{"strategyIds":["strat_v12"],"priority":2,"emailSupport":true,"dashboard":true,"killSwitch":true,"riskManagement":true,"lineSupport":true}',
    isActive: true,
    isTrial: false,
    trialDays: 0,
    sortOrder: 2,
  },
  {
    id: 'pkg_elite',
    name: 'Elite',
    description: 'For Professional Traders — 5 Accounts: Custom Config + VIP Line + 1-on-1 Setup Call',
    priceCents: 4999,
    currency: 'USD',
    billingCycle: 'MONTHLY',
    maxAccounts: 5,
    features: '{"strategyIds":["strat_v12"],"priority":3,"emailSupport":true,"dashboard":true,"killSwitch":true,"riskManagement":true,"lineSupport":true,"customConfig":true,"setupCall":true}',
    isActive: true,
    isTrial: false,
    trialDays: 0,
    sortOrder: 3,
  },
];
